spring:
  #DATABASE
  datasource:
    url: jdbc:h2:mem:aposta
    driverClassName: org.h2.Driver
    username: guiborges
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

aws:
  region: us-east-2

server:
  port: 8080